name: Pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - master
      - releases/*

jobs:
  preflight-check:
    # Prevents running the workflow when a PR is marked as draft.
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if PR is draft
        id: check
        run: |
          if [[ "${{ github.event.pull_request.draft }}" == "true" ]]; then
            skip=true
          else
            skip=false
          fi
          echo "skip=${skip}" >> $GITHUB_OUTPUT
          echo "skip=${skip}"
  Lint:
    needs: preflight-check
    if: needs.preflight-check.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build:all
      - name: Lint
        run: yarn lint:all
  Format:
    needs: preflight-check
    if: needs.preflight-check.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build:all
      - name: Format
        run: yarn format:all
  Circular deps:
    needs: preflight-check
    if: needs.preflight-check.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build:all
      - name: Lint
        run: yarn check_circular_deps:all
  Translation files:
    needs: preflight-check
    if: needs.preflight-check.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build:all
      - name: Translation files
        run: yarn workspace @openshift-assisted/locales run validate_translation_files
  Test:
    needs: preflight-check
    if: needs.preflight-check.outputs.skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build:all
      - name: Lint
        run: yarn test:all
